version: "3.3"

services:
  api:
    build:
      context: ./API_DGForm/
      dockerfile: ./Dockerfile
    ports:
      - "10010:3000"
    container_name: ms_api_nodejs
    expose:
      - "10010"
    # volumes:
    #   - "./API_DGForm:/var/www"
    networks:
      - dg_form_network
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: db_postgres_12
    environment:
      POSTGRES_DB: "db_dgform"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_12_vol:/var/lib/postgres/data"
    expose:
      - "5432"
    networks:
      - dg_form_network
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "5000:8080"
    volumes:
      - "/home/yonattan/proyectos/DGForm/DevOps/Jenkins:/home/jenkins"

volumes:
  postgres_12_vol:

#Red establecida para todos los contendores de dgForm
networks:
  dg_form_network:
