version: "3.3"

services:
  api:
    build:
      context: /home/yonattan/proyectos/dg_form/API_DGForm/
      dockerfile: /home/yonattan/proyectos/dg_form/API_DGForm/Dockerfile
    ports:
      - "10010:3000"
    expose:
      - "10010"
    volumes:
      - "/home/yonattan/proyectos/dg_form/API_DGForm:/var/www"
  db:
    image: postgres:12
    container_name: db_postgres_12
    environment:
      POSTGRES_DB: "db_dgform"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_12_vol:/var/lib/postgres/data"
    expose:
      - "5432"
volumes:
  postgres_12_vol:
